apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-manager
rules:
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["create", "list", "get", "delete", "watch"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "nodes", "events"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-manager-binding
subjects:
- kind: ServiceAccount
  name: scaler-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaler
spec:
  selector:
    matchLabels:
      app: scaler
  replicas: 1
  template:
    metadata:
      labels:
        app: scaler
    spec:
      serviceAccountName: scaler-sa
      containers:
      - name: scaler
        image: scaler:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MAX_JOBS
          value: "10"
        envFrom:
        - configMapRef:
            name: platform-env
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: logs-volume
          mountPath: /logs
      volumes:
      - name: config-volume
        configMap:
          name: jobs-config
      - name: logs-volume
        hostPath:
          path: /Users/purushsimhan/learning/kube-job/logs
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: scaler
spec:
  selector:
    app: scaler
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
